const routes=[
    {
        path:'/',
        component:'@/layouts/first-tier',
        routes:[
            {
                path:'/',
                redirect:'/users'
            },
            {
                path:'/users',
                component:'@/pages/users'
            },
            {
                path:'/personal-center',
                component:'@/layouts/second-tier',
                routes:[
                    {
                        path:'/personal-center',
                        redirect:'/personal-center/personal-center-1'
                    },
                    {
                        path:'/personal-center/personal-center-1',
                        component:'@/pages/personal-center',
                    },
                    {
                        path:'/personal-center/personal-center-2',
                        component:'@/pages/personal-center/personal-center-2',
                    },{
                        path:'/personal-center/personal-center-3',
                        component:'@/pages/personal-center/personal-center-3',
                    },
                    {
                        path:'/personal-center/personal-center-4',
                        component:'@/pages/personal-center/personal-center-4',
                    },
                    {
                        path:'/personal-center/personal-center-5',
                        component:'@/pages/personal-center/personal-center-5',
                    },
                ]
            },
        ]
    },
]
export default routes